compressionLevel: mixed

enableGlobalCache: true

enableScripts: true

logFilters:
  - code: YN0032
    level: discard

nodeLinker: node-modules

npmMinimalAgeGate: 7d

packageExtensions:
  "@fast-check/jest@2.1.1":
    peerDependenciesMeta:
      "@jest/globals":
        optional: true

yarnPath: .yarn/releases/yarn-4.18.0.cjs
